CREATE TABLE CLIENTE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(255),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO(ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO(ID),
    QUANTIDADE INTEGER
);